### ISSUE TITLE
Create tests for existing functions

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/migraph#126]

**Comment by jhollway** [comment]
% done?

**Comment by BBieri** [comment]
63.12 % at the moment @jhollway. Will add some tests today for the read functions which should get us past the 70% mark.

**Comment by BBieri** [comment]
**Update:**  We currently have 78.20% total coverage. Some functions still need to be reworked before being tested. This includes the following functions:

- `read_ucinet()`
- `as_network()` methods (still produce unexpected results)
- `ggatyear()` does not find the "dynamic" layout it tries to use. May be due to an update of `{ggraph}`?

**Comment by jhollway** [comment]
Great, are these new issues?

**Comment by BBieri** [comment]
`read_ucinet()` needs documentation work, some refactoring and maybe some debugging (I ran into troubles when trying to import UCINET files but that might just be due to my unfamiliarity with the format).

**Comment by jhollway** [comment]
Yes, please open as issues.

**Comment by BBieri** [comment]
Update: we're at 88.1% coverage :)
