### ISSUE TITLE
Develop is_ methods

### ISSUE THREAD

**Issue by BBieri** [snlab-ch/migraph#175]
Develop is_ methods that are at the bottom of the is methods R file.

**Comment by jhollway** [comment]
Do you mean introducing more is_ functions or making the current slate of functions S3 methods?

**Comment by BBieri** [comment]
My bad, too quick on the wording. I mean developing the is_functions first and then in the future, we could add them as methods so as to have a more robust and safe way of checking whether a graph object satisfies this or that property.

**Comment by BBieri** [comment]
I added several new `is_` functions and in the process, I was confronted with a "design" issue. Most `is_` functions return a single boolean value since they check concepts at the graph level. However, some of the checks may also happen at the node or edge level (which is the case with `which_loop()` for example) and return a vector of boolean values. I was thus thinking of distinguishing between:

- `is_` functions that operate at the graph level
- `which_` functions that operate at the node or edge level

Added bonus: this option follows the `{igraph}` syntax, which might make users less confused when switching from package to package

What do you think @jhollway ?

**Comment by jhollway** [comment]
Thanks @BBieri , nice idea. The problem with following igraph (or any other) syntax however is then we could introduce conflicts and/or confusion when the functions don’t work as expected because one or the other package was loaded first/second etc. Let me have a think about this. More important is probably to separate out the is_ functions into S3 methods so that tests can be done more efficiently and debugging can relate to a specific implementation.
